---
output: github_document
# output: html_document
md_extensions:
  self_contained: true
editor_options: 
  chunk_output_type: console
---

## DAV 5300 Computational Mathematics and Statistics - Spring 2024

**Instructor:** Jason Bryer, Ph.D. [jason.bryer@ye.edu](mailto:jason.bryer@ye.edu)  
**Meeting Time:** Tuesdays 5:30pm to 7:30pm  
**Office Hours:** Before and after class and online by appointment  
**Teaching Assistant:** Dengyi Liu [dliu6@mail.yu.edu](mailto:dliu6@mail.yu.edu)  

### Course Overview

Deeper math literacy and computational thinking are essential for deeper data literacy. Probability, statistics, and mathematics—especially fundamental linear algebra—are critical to the success of data analysts as they implement increasingly complex solutions. This course is designed to give the non-mathematician practice using mathematical and statistical computational methods in the service of data analytic solutions.

### Attendance

You are expected to attend class to learn the material for the course. Attendance will be recorded for each session. While one absence will not be a problem, several absences will be. That said, if your circumstances warrant missing class, please discuss with me as soon as possible.

### Textbooks

[*Introduction to Modern Statistics*](materials/imstat.pdf) by Mine Çetinkaya-Rundel and Johanna Hardin - This will be the primary textbook.

[*R for Data Science*](https://r4ds.hadley.nz) by Hadley Wickham and Garrett Grolemund - Recommended reference for those new to R.

[*OpenIntro Statistics*](materials/os4.pdf) by David Diaz, Mine Çetinkaya-Rundel, and Christopher D Barr.

### Software

We will make extensive use of [R](http://r-project.org), an open source statistics program and language, however some assignments *may* be completed in Python. Be sure to [install R](http://cran.r-project.org/) and [RStudio](http://rstudio.com) on your own computers within the first few days of the class.

* R - download for [Windows](http://cran.r-project.org/bin/windows/base/), [Mac](http://cran.r-project.org/bin/macosx/), or [Linux](https://cran.r-project.org).
* RStudio - [Download Windows, Mac, or Linux versions from here](https://rstudio.com/products/rstudio/download/#download)

If using Windows, you also need to download [RTools](http://cran.r-project.org/bin/windows/Rtools/).

[LaTeX](https://www.latex-project.org/) is a typesetting language for preparing documents. Documents are written in plain text files. Formatting the document is done using specific markup. If you have used HTML, the framework is similar however instead of using `<TAG></TAG>` syntax, LaTeX uses `\TAG{}` format. We will primarily use [Markdown](https://daringfireball.net/projects/markdown/), and its extension [R Markdown](https://rmarkdown.rstudio.com/) for preparing documents in this class. However, when preparing PDF documents, the Markdown will first be converted to LaTeX before creating the PDF file. As such, a LaTeX converter is necessary. There are LaTeX installers for [Windows (MiKTeX)](http://miktex.org/) and [Mac (BasicTeX)](http://www.tug.org/mactex/morepackages.html). Alternatively, the [`tinytex`](https://yihui.name/tinytex/) R package provides an easier way of installing LaTeX directly from within R:

```
install.packages('tinytex')
tinytex::install_tinytex()
```

The following command will install a core set of packages we will use during the semester. This only needs to be run once per R installation.

```
install.packages(c('openintro','devtools','tidyverse', 'ggplot2',
                   'psych','reshape2','knitr','markdown','shiny','R.rsp',
                   'fivethirtyeight'))
remotes::install_github("jbryer/brickset")
```


### Assignments and Grading

You will be assessed using a variety of methods, namely:

**Labs** (30%) - Labs are designed to provide you an opportunity to apply statistical concepts using statistical software.

**Textbook questions** (15%) - The assigned questions from the textbook provide an opportunity to assess conceptional understandings. Questions are from the *Exercises* section at the end of each chapter.

**Participation** (10%) - You are expected to attend every class and to complete a [one minute paper](https://forms.gle/CD5Qxkq3xtdxSheW8) at the conclusion of class.

**Poster** (25%) - We will hold a poster session on the second to last class. In a group of 2 to 3 students will create poster presenting the results of analysis using a data set of your choice. More details will be provided a few weeks into the class.

**Final exam** (20%) - A multiple choice exam will be given on the last day of class.

**All assignments are due on Sunday.** Assignments submitted late will be penalized. Assignments will not be accepted more than one week after their due date.

The following grading scale will be used for this class.

| Quality of Performance                     | Letter | Grade Range (%) | GPA/Quality Points |
|--------------------------------------------|--------|-----------------|--------------------|
| Excellent - work is of exceptional quality | A.     | 93 – 100.       | 4.0                |
|                                            | A.     | 90 – 92.9.      | 3.7                |
| Good - work is above average               | B+.    | 87 – 89.9.      | 3.3                |
| Satisfactory                               | B      | 83 – 86.9       | 3.0                |
| Below Average                              | B-     | 80 – 82.9       | 2.7                |
| Poor                                       | C+     | 77 – 79.9       | 2.3                |
|                                            | C      | 70 – 76.9       | 2.0                |
| Failure                                    | F      | < 70            | 0.0                |


### Schedule

*Tentative and subject to change*

```{r, echo=FALSE, results='asis'}
options(knitr.kable.NA = '')
schedule <- readxl::read_excel('Schedule.xlsx', sheet = 2) |>
	# dplyr::select(!Link) |> 
	tidyr::replace_na(list(Assignments = '', Readings = ''))

links <- which(!is.na(schedule$Link))
if(length(links) > 0) {
	schedule[links,]$Topic <- paste0("<a href='", schedule[links,]$Link, "'>",
									 schedule[links,]$Topic, "</a>")
}
# schedule$Topic <- sapply(schedule$Topic, markdown::mark) |> unname()
schedule$Readings <- sapply(schedule$Readings, markdown::mark) |> unname()
schedule$Assignments <- sapply(schedule$Assignments, markdown::mark) |> unname()
schedule$Link <- NULL
knitr::kable(schedule, format = 'html', escape = FALSE)
```


### University Policies and Resources

#### Accessibility and Accomodations

The Office of Disability Services collaborates with students, faculty, and staff to provide reasonable accommodations and services to students with disabilities. Students with disabilities who are enrolled in this course and who will be requesting documented disability-related accommodations should make an appointment with the Office of Disability Services, during the first week of class. Once you have been approved for accommodations, please submit your accommodation letter to ensure the successful implementation of those accommodations. For more information, please visit http://yu.edu/Student-Life/Resources-and-Services/Disability-Services/Links to an
external site.

#### Academic Integrity

The submission by a student of any examination, course assignment, or degree requirement is assumed to guarantee that the thoughts and expressions therein not expressly credited to another are literally the student’s own. Evidence to the contrary will result in appropriate penalties. For more information, visit http://yu.edu/registrar/grad-catalog/Links to an external site.

#### Student Support Services

If you need any additional help, please visit Student Support Services at http://yu.edu/academics/services/Links to an external site..
